import { Download, FileText, Code, FileCode } from 'lucide-react'
import { useState } from 'react'
import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'

export function ExportButton({ analysisData, elementId = 'analysis-content' }) {
    const [isOpen, setIsOpen] = useState(false)
    const [isExporting, setIsExporting] = useState(false)

    const exportAsPDF = async () => {
        setIsExporting(true)
        try {
            const element = document.getElementById(elementId)
            if (!element) {
                console.error('Element not found for PDF export')
                return
            }

            const canvas = await html2canvas(element, {
                scale: 2,
                logging: false,
                useCORS: true
            })

            const imgData = canvas.toDataURL('image/png')
            const pdf = new jsPDF({
                orientation: 'portrait',
                unit: 'px',
                format: 'a4'
            })

            const imgWidth = pdf.internal.pageSize.getWidth()
            const imgHeight = (canvas.height * imgWidth) / canvas.width

            pdf.addImage(imgData, 'PNG', 0, 0, imgWidth, imgHeight)
            pdf.save(`phishscope-analysis-${analysisData.id || 'report'}.pdf`)
        } catch (error) {
            console.error('PDF export failed:', error)
            alert('Failed to export PDF. Please try again.')
        } finally {
            setIsExporting(false)
            setIsOpen(false)
        }
    }

    const exportAsJSON = () => {
        const jsonString = JSON.stringify(analysisData, null, 2)
        const blob = new Blob([jsonString], { type: 'application/json' })
        downloadBlob(blob, `phishscope-analysis-${analysisData.id || 'data'}.json`)
        setIsOpen(false)
    }

    const exportAsMarkdown = () => {
        const markdown = generateMarkdown(analysisData)
        const blob = new Blob([markdown], { type: 'text/markdown' })
        downloadBlob(blob, `phishscope-analysis-${analysisData.id || 'report'}.md`)
        setIsOpen(false)
    }

    const downloadBlob = (blob, filename) => {
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = filename
        document.body.appendChild(a)
        a.click()
        document.body.removeChild(a)
        URL.revokeObjectURL(url)
    }

    const generateMarkdown = (data) => {
        return `# PhishScope Analysis Report

## URL
${data.url || 'N/A'}

## Analysis Date
${data.timestamp || new Date().toISOString()}

## Status
${data.status || 'Unknown'}

## Findings

${JSON.stringify(data.findings || {}, null, 2)}

---
Generated by PhishScope
`
    }

    return (
        <div className="relative">
            <button
                onClick={() => setIsOpen(!isOpen)}
                className="flex items-center gap-2 px-4 py-2 bg-white/50 dark:bg-dark-card/50 backdrop-blur-md border border-white/20 dark:border-dark-border/20 rounded-lg hover:bg-white/70 dark:hover:bg-dark-card/70 transition-all duration-300"
                disabled={isExporting}
            >
                <Download className="w-4 h-4" />
                <span>{isExporting ? 'Exporting...' : 'Export'}</span>
            </button>

            {isOpen && (
                <>
                    <div
                        className="fixed inset-0 z-40"
                        onClick={() => setIsOpen(false)}
                    />
                    <div className="absolute right-0 mt-2 w-48 bg-white dark:bg-dark-card backdrop-blur-xl border border-white/20 dark:border-dark-border/20 rounded-lg shadow-glass z-50">
                        <button
                            onClick={exportAsPDF}
                            className="w-full flex items-center gap-3 px-4 py-3 hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors text-left rounded-t-lg"
                            disabled={isExporting}
                        >
                            <FileText className="w-4 h-4" />
                            <span>Export as PDF</span>
                        </button>
                        <button
                            onClick={exportAsJSON}
                            className="w-full flex items-center gap-3 px-4 py-3 hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors text-left"
                        >
                            <Code className="w-4 h-4" />
                            <span>Export as JSON</span>
                        </button>
                        <button
                            onClick={exportAsMarkdown}
                            className="w-full flex items-center gap-3 px-4 py-3 hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors text-left rounded-b-lg"
                        >
                            <FileCode className="w-4 h-4" />
                            <span>Export as Markdown</span>
                        </button>
                    </div>
                </>
            )}
        </div>
    )
}
